# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('tag', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
