# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
